{% set version = '1.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lmtp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lmtp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lmtp/lmtp_{{ version }}.tar.gz
  sha256: 7619e671129d364fbe2acc6d82f723a1ecddc4037702ef0d36e36e629645fe81

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-superlearner
    - r-checkmate >=2.1.0
    - r-cli
    - r-data.table >=1.13.0
    - r-future >=1.17.0
    - r-generics
    - r-nnls
    - r-origami
    - r-progressr
    - r-schoolmath
  run:
    - r-base
    - r-r6
    - r-superlearner
    - r-checkmate >=2.1.0
    - r-cli
    - r-data.table >=1.13.0
    - r-future >=1.17.0
    - r-generics
    - r-nnls
    - r-origami
    - r-progressr
    - r-schoolmath

test:
  commands:
    - $R -e "library('lmtp')"           # [not win]
    - "\"%R%\" -e \"library('lmtp')\""  # [win]

about:
  home: https://beyondtheate.com/
  dev_url: https://github.com/nt-williams/lmtp
  license: AGPL-3.0-only
  summary: Non-parametric estimators for casual effects based on longitudinal modified treatment
    policies as described in Diaz, Williams, Hoffman, and Schenck <doi:10.1080/01621459.2021.1955691>,
    traditional point treatment, and traditional longitudinal effects. Continuous, binary,
    categorical treatments, and multivariate treatments are allowed as well are censored
    outcomes. The treatment mechanism is estimated via a density ratio classification
    procedure irrespective of treatment variable type. For both continuous and binary
    outcomes, additive treatment effects can be calculated and relative risks and odds
    ratios may be calculated for binary outcomes.
  license_family: AGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: lmtp
# Title: Non-Parametric Causal Effects of Feasible Interventions Based on Modified Treatment Policies
# Version: 1.4.0
# Authors@R: c(person(given = "Nicholas", family = "Williams", role = c("aut", "cre", "cph"), email = "ntwilliams.personal@gmail.com", comment = c(ORCID = "0000-0002-1378-4831")), person(given = "Ivan", family = "Diaz", email = "Ivan.Diaz@nyulangone.org", role = c("aut", "cph"), comment = c(ORCID = "0000-0001-9056-2047")))
# Description: Non-parametric estimators for casual effects based on longitudinal modified treatment policies as described in Diaz, Williams, Hoffman, and Schenck <doi:10.1080/01621459.2021.1955691>, traditional point treatment, and traditional longitudinal effects. Continuous, binary, categorical treatments, and multivariate treatments are allowed as well are censored outcomes. The treatment mechanism is estimated via a density ratio classification procedure irrespective of treatment variable type. For both continuous and binary outcomes, additive treatment effects can be calculated and relative risks and odds ratios may be calculated for binary outcomes.
# Depends: R (>= 2.10)
# License: AGPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.3.1
# Imports: stats, nnls, cli, R6, generics, origami, future (>= 1.17.0), progressr, data.table (>= 1.13.0), checkmate (>= 2.1.0), SuperLearner, schoolmath
# URL: https://beyondtheate.com/, https://github.com/nt-williams/lmtp
# BugReports: https://github.com/nt-williams/lmtp/issues
# Suggests: testthat (>= 2.1.0), covr, rmarkdown, knitr, ranger, twang
# NeedsCompilation: no
# Packaged: 2024-06-27 03:27:38 UTC; ntw2117
# Author: Nicholas Williams [aut, cre, cph] (<https://orcid.org/0000-0002-1378-4831>), Ivan Diaz [aut, cph] (<https://orcid.org/0000-0001-9056-2047>)
# Maintainer: Nicholas Williams <ntwilliams.personal@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-06-27 03:40:02 UTC
